### PR TITLE
Justified Gallery

### PR DESCRIPTION
**Pull request by amcolash**
This PR adds in a justified gallery to solve https://github.com/thumbsup/thumbsup/issues/86. In order to use this theme fully, the associated PR in thumbsup must be merged in first (https://github.com/thumbsup/thumbsup/pull/146).

### CODE REVIEW

**Comment by amcolash** [comment]
Screenshot
image

**Comment by piccolbo** [comment]
I would love to see this style used consistently across a site including index, folders and albums.  Not only I like the visual consistency but also I hate to see my pictures arbitrarily reframed to fit a grid. If they looked good square, I would  crop them so myself.  I am not sure how complex the implementation would be.

**Comment by amcolash** [comment]
I do like that idea, however I am not entirely sure if that makes sense for albums. Could you find an example of a site showing albums that are justified? It gets tricky because of album names :disappointed:

**Comment by amcolash** [comment]
I have a sample gallery hosted on heroku, hopefully this will let us iterate to get the right design before deploying this new change. Take a look: https://thumbsup-testing.herokuapp.com/

**Comment by piccolbo** [comment]
As far as albums, I don't have an example, but my now defunct smugmug gallery was organized that way so I speak from experience. Don't think about albums, galleries and what not for a moment, let's go up one level of abstraction. We have a collection of pictures to be displayed with a title for the collection and a short text for each picture (filename, title, description, metadata, whatever). Then we have an action in response to a click on an image: open another collection, open a lightbox, open a full size pic. So an album page is a collection of pics, one for each album, with a gallery name as snippet:
```
[pic          ][pic          ][pic          ]
Venice          Florence       London
```
Click on say the Venice pic and you get the Venice collection:
```
[pic        ][pic               ][pic                    ]
St. Mark      Rialto bridge       Bridge of Sighs
```
Now Click on the Rialto bridge and you go into the lightbox focused on that pic. Makes sense? Now what if we want to pull say 2 pics from each album to appear in to an album page? Does my abstraction still work? I think so,
```
[pic 1 album 1][pic 2 album 1][pic 1 album 2][pic 2 album 2][pic 1 album 3][pic 2 album 3]
Venice          Venice         London         London          Florence        Florence
```
It's still pics with text snippets. Only additional rule could be not to show snippets that repeat the previous one, as in
```
[pic 1 album 1][pic 2 album 1][pic 1 album 2][pic 2 album 2][pic 1 album 3][pic 2 album 3]
Venice                         London                          Florence          
```
And you may want different styles for a caption that's valid only for one picture and one that's valid for all the following ones, the latter needing a bit more prominence. But I don't think it's a fundamentally different problem: show pics at their original aspect ratio, at similar scales, with some text that's not covering them, or only on hover, using up all the screen space. If I find an example on line I will share it. I had some trouble aligning that ASCII art above, so please rely on your imagination if things don't display correctly.

**Comment by piccolbo** [comment]
When I said "I speak from experience" I meant the organization I described is possible, not that I know for a fact it's the best -- I believe that, but opinions are many and variable. Just to be clear.

**Comment by piccolbo** [comment]
Here is an example (but I hate the heavy overlays: text below or above the picture or on hover only is all good for me, hover preferred):https://justifiedgrid.com/sources/flickr/collections-multi-level/

Multi-level collections, one representative image per node. Bottom level uses lightbox. It's marketing material, so there is other crud around the gallery but if you just look at the concept, that is it.

**Comment by amcolash** [comment]
I see where you are coming from. Let's take a step back and simplify things. When on an album page with all nested images shown, right now it is justified and has caption on hover. Are you essentially just asking for that at a higher level as well (i.e. album preview image + title on hover)? If so, that should definitely be doable.

That being said, the current cards theme has that info always shown and I don't want to deviate too much away from that without a sign-off from @rprieto. So far, I have tried to keep things looking pretty similar to what they were like previously.

Consistency will definitely bring this theme together, but I am a bit worried that if your album has a portrait-orientated picture that the album info will get cut pretty often. Another option is to make those album images much larger than the thumbnails in the gallery. I am not entirely sure of how an album chooses it's front image (though I would assume that it just chooses the first image in the folder). 

I can try this idea out and will post updates when I get time. @piccolbo Did you like the test gallery for inside an album? Hopefully we can get a really nice looking album view as well too!

**Comment by piccolbo** [comment]
Yep, instead of many different concepts, one has a collection of images,
which can contain directly images or other collections. Each collection is
represented at the higher level by one or a few images. And hover is my
preference because it is unobtrusive, but whatever the choice is, keep it
consistent across levels. Would love to give it a spin when you have
something.

**Comment by rprieto** [comment]
Lots of interesting ideas! I agree it's down to preferences. For example when you say"if they looked good square I would crop them myself", iOS always displays square albums and thumbnails in the Photos app.

I think that's the power of themes in thumbsup, we can have a square theme and a "justified" one.

@piccolbo I do really like the look of the gallery you shared at https://justifiedgrid.com/sources/flickr/collections-multi-level/. It makes me think that maybe it should be a new theme that has "justified" everything, albums and thumbnails. And then we can leave the Cards theme as it is now.

@amcolash your preview on Heroku looks great, I'm happy to merge it as-is, we just have to agree if it's a new theme.

@piccolbo, can you clarify what you meant by

> Yep, instead of many different concepts, one has a collection of images, which can contain directly images or other collections. Each collection is represented at the higher level by one or a few images.

Unless I misunderstood this is exactly how Thumbsup works, except we call "collections" albums.

**Comment by rprieto** [comment]
I forgot to answer some questions!

- I like the idea of a title for each album, there is an open issue about that.
- yes for now the album picks the first image as a preview (or images, depending on the theme)
- if like to avoid hovers on official themes as they don't work on mobile devices
- @piccolbo have a look at this theme https://photos.techxplorer.com (from https://github.com/thumbsup/thumbsup/issues/142), it might match what you're after, square thumbnails excepted 🙂

I'm not sure we'll be able to create themes that fit everyone's views, so my vision is to have a range of officiel themes that showcase what's possible (different designs, different features) and everyone can fork and customise to suit their taste! An official "justified" theme definitely would be welcome.

**Comment by piccolbo** [comment]
@rprieto I was just responding to @amcolash on how to do justified albums.  Since you don't see a problem with justified albums, maybe there is no need to dig any deeper. My terminology with albums, galleries, etc is a little fuzzy. At each level of a hierarchy thumbsup picks a certain set of pics to display (say one per sub-album, or all of them at the bottom level), then there is a separate decision on how to display them. If you see it this way, there is no problem doing justified galleries at every level.

**Comment by piccolbo** [comment]
As far as techexplorer, I am not sure why you bring it up.  I like it it has a uniform display at each level and that text is off the pic. But it's not justified, as you note. I see why hovers are a problem on mobile.

**Comment by rprieto** [comment]
I mentioned that theme for inspiration because of the uniform display, and the fact it doesn't use overlays to show the details :+1:

Should I create a new repo for the "justified" theme? (or any better name?)

**Comment by amcolash** [comment]
@rprieto I think making a new repo (that is essentially a dupe of this one, as a starting point) would be a good choice. Then there are no surprises for users who currently like the cards theme. I can then work on getting my PR set. I do like the idea of keeping all aspects justified for the final theme.

Not sure what to call it, but I think justified works. The word "modern" comes to mind when I see the style of the justified albums though and may describe it better - though it is vague. Flow is also a nice name, since the images flow next to each other.

**Comment by amcolash** [comment]
@piccolbo see my previous [comment](https://github.com/thumbsup/theme-cards/pull/3#issuecomment-468758783) for the link to the test gallery

**Comment by piccolbo** [comment]
+1 for justfied. As far as @amcolash test gallery, first thanks for setting it up. The top level doesn't have enough pictures for me to know if it's horizontally justified, and the bottom level looks good. The top level overlays text onto the (only) picture. The bottom level uses overlays on hover, and much smaller and more discreet (better IMHO). Unless there is a good reason, I suggest find one good style and keep it at every level. Let the pics shine.

Orthogonal to justification and consistency, here are a few personal preferences (I am more than willing to implement them in my own fork, but just in case people want to adopt any of them):

1. No rounded corners. Any reframing of a pic that ignores content should be avoided. Just go around a look at the few galleries  and count how many use rounded corners (500px, unsplash, flickr)
2. No fixed overlays: There should be a view that shows only pure, unadulterated pixels and ideally that should be the first view. My preference is to show caption and/or metadata on hover only, but @rprieto brought up that doesn't apply to mobile. I don't have a clean answer to that as I don't look at pics on tiny screens. Again, check out proprietary galleries (500px, unsplash, flickr). They all show metadata or captions only on hover. Their mobile versions (just checked) don't show metadata on mobile, on hover or otherwise. Makes sense you'd have less info on a tiny screen, not more.

**Comment by rprieto** [comment]
Good comments @piccolbo. I'm sold on the hover for metadata on desktop. @amcolash your test gallery looks great.

Also agreed on using a similar style for albums / photos sounds good, as long as it's clear if a card is an album or not. Could be similar "styles", but still including a tag line like `17 photos` in addition to the album name.

I quite like `flow` as a theme name! In the end all the other themes are already justified - in the sense they run edge-to-edge. I'll create the repo and we can always change it before going live.

**Comment by amcolash** [comment]
Sorry @piccolbo , I have been pretty busy the past few days and have not been able to update to make things a bit more unified (just a bit of time here and there to respond to the comments).

I really like the idea of having a slightly different experience for mobile / desktop as they are very different ways to consume media - especially for a photo gallery.

I started looking around at other places for inspiration on justified galleries and really like the look of flickr. Photos in a gallery are justified just like how they are now. The album view is really slick while still giving the impression of justified and sleek.

It looks great on mobile and desktop without much in terms of visual changes

image

image

image

Now I am not saying that we need to completely copy and paste flickr, but I do like the context it gives in the album mode, while still feeling natural when moving inside the album

**Comment by amcolash** [comment]
I have also looked at 500px and while their album view is a bit different, it still is nice.

Here are links to the 2 mentioned sites

flickr albums: https://www.flickr.com/photos/flickr/galleries
flickr single album: https://www.flickr.com/explore

500px albums: https://500px.com/adnanbubalo/galleries
500px single album: https://500px.com/adnanbubalo/galleries/favorites


Interestingly, google photos does something pretty similar to 500px but also rounds the album corners slightly. The base images are not rounded however, which is odd since photos are sharp corners but albums are round.

Edit: Found this wordpress theme named pinhole and I love the way they justified the albums as suggested. I think cleaning up cards a bit could make it look something like this: https://demo.mekshq.com/?theme=pinhole&landing=1

**Comment by rprieto** [comment]
Hi, sorry for the delay: https://github.com/thumbsup/theme-flow is now ready.
@amcolash I gave you write access to that repo. Can you please apply your changes over there?

edit: the Pinhole theme you found looks great!

**Pull request closed without merging**
